### PR TITLE
#30: Bringing back Drupal' default body CSS classes

### PR DESCRIPTION
**Pull request by netlooker**
After a talk with colleagues we decided to bring back Drupal' default body tag CSS classes.
The reason for that is Drupal7 has a lot of features based on the specific CSS classes.
To keep backward compatibility and to avoid some unexpected issues we will proceed with this solution.
In future we should rethink that approach but currently we don't have enough informations to address this issue in other way.

### CODE REVIEW

**Comment by drupol** [comment]
Oh damn that hurts...

**Comment by netlooker** [comment]
Ok, so let's do the cutting in a more granular way.

**Comment by drupol** [comment]
👍

**Comment by drupol** [comment]
I feel better ... Haaaaa :-)

**Comment by netlooker** [comment]
Before the merge I will use the last commit as a reference for the build to check how the platform-dev behaves and after that we can proceed with this issue.

**Comment by drupol** [comment]
7686178464_fdc8ea66c7

**Comment by netlooker** [comment]
I know that's a painful thing but as long as we don't have an alternative we need to proceed with this and address the issue later :)

**Comment by drupol** [comment]
👍

**Comment by Fefaine** [comment]
:+1:

**Pull request merged**
