### PR TITLE
NEPT-1355: Remove @ignore annotation comments, a ruleset has been add…

### PR DESCRIPTION
**Pull request by ku-enza**
…ed in qa-automation for drupal wrappers.

### CODE REVIEW

**Comment by drupol** [comment]
We must update composer.json with

`"ec-europa/qa-automation": "^3.0"`

**Comment by ku-enza** [comment]
it worked with ~3.0.0 .... but if you find that's better :)

**Comment by drupol** [comment]
I know I know.

But I think we should use ^3.0.

If you do: `composer require "ec-europa/qa-automation" --dev` it will use that notation as well.

**Review by drupol — APPROVED** [review]
All good for me.

**Pull request merged**
