### PR TITLE
Issue #455: Update composer package phptaskman/drupal.

### LINKED ISSUE #455: Update phptaskman vesrion
Drupal and changelog packages have been updated.

The issue with the database password has been solved.

### PR DESCRIPTION
**Pull request by aritomelo**
Fix #455

### CODE REVIEW

**Comment by drupol** [comment]
I don't think this should be done.

By using those branches, then it means that it won't work anymore with `PHP ^5.6`

**Comment by donquixote** [comment]
@drupol there was a bug in php-taskman, which prevented the use of a database password..
can we get this fix without the full upgrade?

**Comment by drupol** [comment]
Of course, it has been fixed since then.

**Comment by donquixote** [comment]
@drupol So what is the minimum version we need to update to get this fix?

**Comment by drupol** [comment]
Just 0.1.23 for php-taskman/drupal: https://github.com/php-taskman/drupal/releases/tag/0.1.23

**Comment by drupol** [comment]
You can use 0.1.24 to fix the issue.

**Review by donquixote — APPROVED** [review]
Now I like it :)

**Pull request merged**
