### PR TITLE
NEPT-1546: Use an Attributes container for handling template attributes.

### PR DESCRIPTION
**Pull request by drupol**

### CODE REVIEW

**Comment by voidtek** [comment]
I like this improvement ... 👍

**Comment by drupol** [comment]
We need to fix the class, the tests, and the process hooks first.

**Comment by voidtek** [comment]
of course .... :)

**Comment by voidtek** [comment]
:+1:

**Comment by ku-enza** [comment]
It's a big pull request, nice work! :+1:

**Review by ku-enza — APPROVED** [review]
Nothing to add so far. :+1:

**Pull request merged**
