### PR TITLE
#53: Let theme customize the behavior of the hook_field_attach_view_alter().

### PR DESCRIPTION
**Pull request by drupol**

### CODE REVIEW

**Comment by Fefaine** [comment]
@drupol Travis reports 11 phpcs violations

**Comment by drupol** [comment]
Hi @delphine,

There's a bug in QA-Automation 3.0.2 and I'm waiting for an update before triggering the tests again.

**Comment by Fefaine** [comment]
okido tx

**Review by voidtek — APPROVED** [review]
It's fine for me.

**Pull request merged**
