### PR TITLE
#130: Optimize Attributes (7.x-2.x), rebase II

### PR DESCRIPTION
**Pull request by donquixote**
@drupol

I did some heavy rebasing, so that:
- Tests pass after every commit. (*)
- Every known behavior change has its own commit, which comes before the big rewrite.
- The big rewrite does not change behavior in any known way. No tests change.
- Every commit that changes behavior is marked as "(beh)". Maybe you have a better idea?

I also changed some behavior in a way that is more backwards compatible.

(*) How to run unit tests for every commit?

    git rebase -i --exec "phpunit --stop-on-failure" 7.x-2.x

How to generate xray tests after every commit?

    git rebase -i --exec "php tests/generate.php" COMMIT_ID

(here COMMIT_ID is the first one where the xray stuff was introduced)

## Reviewing tasks

Decide if
- the behavior changes are acceptable for 7.x-2.x branch.
- the new behavior is more reasonable than the old behavior, in those cases where it is changed.
- git history is ok like this.

Known issues:
I think I have some issue numbers wrong in commit messages.

### CODE REVIEW

**Comment by donquixote** [comment]
See https://help.github.com/articles/why-are-my-commits-in-the-wrong-order/

Commits are displayed in chronological order instead of topological order on https://github.com/ec-europa/atomium/pull/183/commits.

**Comment by donquixote** [comment]
Run phpunit on all commits in the branch:
`git rebase -i --exec "phpunit --stop-on-failure" 7.x-2.x^^`

(7.x-2.x^^ is the last common ancestor of 7.x-2.x and 7.x-3.x, and this PR branch is based on that.)

Careful! Only do this on a linear sequence of commits, otherwise it may change commit history!

**Comment by donquixote** [comment]
> Commits are displayed in chronological order instead of topological order

So better review on your own machine.

**Comment by drupol** [comment]
@donquixote ,

I'm doing the careful review of this branch.
Could you tell me why do we need to maintain a list of valid attribute names in `AttributesUtil` ?
Can't we get rid of it ?

**Comment by drupol** [comment]
*WIP* *WIP* Tasks to do for this amazing PR:

- [ ] Rebase and reduce the amount of commits
- [ ] Remove empty lines after method/function definition
- [ ] Prepend an empty line before `return` statements

**Comment by drupol** [comment]
Closing this.

Find the new rebased branch from this here: #203

**Pull request closed without merging**
