### PR TITLE
#142: Attributes->offsetGet() should return by value, not by reference.

### PR DESCRIPTION
**Pull request by donquixote**
@drupol I mentioned this on hangouts before..
Is there something that would break if we change it?

### CODE REVIEW

**Comment by drupol** [comment]
Hi,

I remember I had to do that to allow us to alter values by doing this:

```php
$attributes_object[$attribute_name]['key'] = 'value';
```

As `$attributes_object[$attribute_name]` is an array(), if you want to be able to alter it, you need the return by reference.

This issue could be fixed using an object for storing single attributes like in [HtmlTag](https://github.com/drupol/htmltag).

**Comment by donquixote** [comment]
Can we make a test case for this?
I doubt that it works as advertised in current master.

**Review by drupol — APPROVED** [review]
I tried to reproduce the reason why I needed it, without success.
I guess this is a mistake.
I'm approving this.

**Comment by drupol** [comment]
Closed in favor of #207

**Pull request closed without merging**
